project:
  type: book
  output-dir: docs

engine: knitr
filters:
  - webr

date: "last-modified"
date-format: iso
institute: "Wilfrid Laurier University"
number-depth: 2
author: "Dr. Devan Becker"
execute:
    warning: false

book:
  title: "STAR Notes"
  subtitle: "Simulation, Theory, and Application of Regression"
  author: "Dr. Devan Becker"
  date: "last-modified"
#  repo-url: https://github.com/DB7-CourseNotes/ST362-Regression-Course-Notes
  page-footer:
    left: |
      Copyright Devan Becker, released under Creative Commons Attribution-ShareAlike 4.0.
  page-navigation: true
  sidebar: 
    collapse-level: 1
  chapters:
    - index.qmd
    - part: OLS Basics
      chapters:
        - L01-Introduction.qmd
        - L02-Fitting_Straight_Lines.qmd
        - L03-Residuals.qmd
        - L04-Matrix_Form.qmd
        - L05-General_Regression.qmd
        - L06-Extra_Sums_of_Squares.qmd
        - L07-Exampless.qmd
        - L08-Hat-Resid_Plots-Cook.qmd
        - L09-Analysing-Resids.qmd
        - L10-Extra_Topics.qmd
        - L11-Wrong_Model.qmd
    - part: Choosing Models
      chapters:
        - L12-NonLinear.qmd
        - L13-Transforming_Response.qmd
        - L14-Modelling_Transformations.qmd
        - L15-Multicollinearity.qmd
        - L16-Dummies.qmd
        - L17-Example_Analysis_mtcars.qmd
        - L18-Modelling_Poorly.qmd
    - part: Advanced Topics
      chapters:
        - L19-Regularization.qmd
        - L20-Logistic.qmd
    - part: Review
      chapters:
        - L22-Review.qmd
  appendices:
    - Lb02-OLS_Estimates.Rmd
    - Lb03-MSE.Rmd
    - Lb04-R_Matrix_Form.Rmd
    - Lb05-ANOVA-R2-F_test-CI.Rmd
    - Lb11-R_hat_resids_cook.Rmd
    - Lb12-Corr_in_Betas.qmd
    - Lb13-Wrong_Model.Rmd
    - Lb15-Transformations.Rmd
    - Lb16-Regression_with_Dummies.Rmd
    - Lb17-Multico.Rmd
    - Lb18-Backwards_Selection_is_Bad.Rmd
    - Lb19-Permutation.qmd

format:
  html:
    theme:
      light: [flatly, smaller_lists.scss]
      dark: [darkly, smaller_lists.scss]
    mainfont: ubuntu, sans-serif
    code-fold: true
    code-summary: "Show the code"
